# 

In [22]:
import torch

x = torch.tensor(2.0) #scalar
y = torch.tensor(9.0)

x + y, x*y, x/y, x**y

(tensor(11.), tensor(18.), tensor(0.2222), tensor(512.))

In [ ]:
torch.arrange(3) #vector

In [ ]:
torch.arrange(6).reshape(3, 2) #matrix

In [ ]:
torch.arange(24).reshape(2, 3, 4) #tensor (height, width, channel)

In [4]:
A = torch.arange(6, dtype=torch.float32).reshape(2, 3)
B = A.clone()  # Assign a copy of A to B by allocating new memory
A, A + B

(tensor([[0., 1., 2.],
         [3., 4., 5.]]),
 tensor([[ 0.,  2.,  4.],
         [ 6.,  8., 10.]]))

In [5]:
A * B #(hadmard product)

tensor([[ 0.,  1.,  4.],
        [ 9., 16., 25.]])

In [11]:
a = 0
X = torch.arange(24).reshape(2, 3, 4)
a + X, (a * X).shape

(tensor([[[ 0,  1,  2,  3],
          [ 4,  5,  6,  7],
          [ 8,  9, 10, 11]],
 
         [[12, 13, 14, 15],
          [16, 17, 18, 19],
          [20, 21, 22, 23]]]),
 torch.Size([2, 3, 4]))

In [13]:
a = 2
X = torch.arange(24).reshape(2, 3, 4)
a + X, (a * X).shape

(tensor([[[ 2,  3,  4,  5],
          [ 6,  7,  8,  9],
          [10, 11, 12, 13]],
 
         [[14, 15, 16, 17],
          [18, 19, 20, 21],
          [22, 23, 24, 25]]]),
 torch.Size([2, 3, 4]))

In [15]:
#sum along which axis with 
tensor.cumsum(axis=0) # sum along 0

tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]],

        [[12, 14, 16, 18],
         [20, 22, 24, 26],
         [28, 30, 32, 34]]])

In [16]:
torch.dot #dot product

RuntimeError: 1D tensors expected, but got 0D and 1D tensors

In [17]:
#matrix-vector, each row of matrix dots with vector
(torch.Size([2, 3]), torch.Size([3]), tensor([ 5., 14.]), tensor([ 5., 14.]))

NameError: name 'tensor' is not defined

In [ ]:
torch.mm #matrix multiplication

In [18]:
u = torch.tensor([3.0, -4.0])
torch.norm(u) #calculates norm

tensor(5.)

In [31]:
A = torch.arange(6).reshape(3,2)
A

tensor([[0, 1],
        [2, 3],
        [4, 5]])

In [32]:
A.T

tensor([[0, 2, 4],
        [1, 3, 5]])

In [28]:
A.T.T

tensor([[0, 1],
        [2, 3],
        [4, 5]])

In [33]:
A = torch.arange(24).reshape(2, 3, 4).float()
A.sum(axis=0).shape, A.sum(axis=1).shape, A.sum(axis=2).shape #skip shape of axis u on

(torch.Size([3, 4]), torch.Size([2, 4]), torch.Size([2, 3]))

In [34]:
A = torch.arange(24).reshape(2, 3, 4).float()
torch.linalg.norm(A) #flattens entire tensor

tensor(65.7571)